/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.PreparedStatement;
import java.util.Arrays;
import javax.swing.JOptionPane;
import metodes.GUI_UF3;
import projecte.Jugador;
import projecte.Projecte;
import static projecte.Projecte.MAX_JUGADORS;

/**
 *
 * @author alumne
 */
public class GUI_exemple extends javax.swing.JFrame {

    //Usada per saber si hi ha alguna fila de la taula seleccionada, i quina és.
    private static int filaSel = -1;
    private int casellabuida = -1;

    /**
     * Creates new form GUI_exemple
     */
    public GUI_exemple() {
        initComponents();
        inicialitzaComponents();
    }

    private void inicialitzaComponents() {
        //Si no han selecionat cap fila desactivo els botons de borrar i modificar.
        boto_borrar.setEnabled(false);
        boto_modificar.setEnabled(false);

        casellabuida = Projecte.inicialitzarVariables();

        GUI_UF3.carregaTaula(new String[]{"Fila", "Nom", "Nacionalitat", "Equip", "Pes", "Alçada", "Salari", "Titular"},
                transformaDades(Projecte.getArray()), Taula);

    }

    public static Object[][] transformaDades(Jugador[] dades) {
        Object[][] resultat = new Object[dades.length][8];
        //Variable per comptar el número de pilots en dades que hi ha a l'array de dades
        int omplerts = 0;

        for (int i = 0; i < dades.length; i++) {
            if (dades[i].isOmplert()) {
                resultat[omplerts][0] = i;
                resultat[omplerts][1] = dades[i].getNom();
                resultat[omplerts][2] = dades[i].getNacionalitat();
                resultat[omplerts][3] = dades[i].getEquip();
                resultat[omplerts][4] = dades[i].getPes();
                resultat[omplerts][5] = dades[i].getMida();
                resultat[omplerts][6] = dades[i].getSalari();
                resultat[omplerts][7] = dades[i].isTitular();
                omplerts++;
            }
        }
        //Retornem només els pilots plens
        return Arrays.copyOf(resultat, omplerts);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        Taula = new javax.swing.JTable();
        casellaNom = new javax.swing.JTextField();
        casellaNacionalitat = new javax.swing.JTextField();
        casellaEquip = new javax.swing.JTextField();
        casellaPes = new javax.swing.JTextField();
        casellaMida = new javax.swing.JTextField();
        casellaSalari = new javax.swing.JTextField();
        Nom = new javax.swing.JLabel();
        Nacionalitat = new javax.swing.JLabel();
        Equip = new javax.swing.JLabel();
        Pes = new javax.swing.JLabel();
        Alçada = new javax.swing.JLabel();
        Salari = new javax.swing.JLabel();
        opcio_titular = new javax.swing.JRadioButton();
        opcio_no_titular = new javax.swing.JRadioButton();
        boto_inserir = new javax.swing.JButton();
        boto_borrar = new javax.swing.JButton();
        boto_modificar = new javax.swing.JButton();
        Text = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        imatge1 = new javax.swing.JLabel();
        imatge2 = new javax.swing.JLabel();
        Boto_sortir = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setBackground(java.awt.Color.green);
        jScrollPane1.setForeground(java.awt.Color.green);

        Taula.setBackground(java.awt.Color.green);
        Taula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Nacionalitat", "Equip", "Pes", "Alçada", "Salari"
            }
        ));
        Taula.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Taula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaulaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Taula);

        casellaNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casellaNomActionPerformed(evt);
            }
        });

        casellaSalari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casellaSalariActionPerformed(evt);
            }
        });

        Nom.setText("Nom");

        Nacionalitat.setText("Nacionalitat");

        Equip.setText("Equip");

        Pes.setText("Pes");

        Alçada.setText("Alçada");

        Salari.setText("Salari");

        buttonGroup1.add(opcio_titular);
        opcio_titular.setSelected(true);
        opcio_titular.setText("Titular");

        buttonGroup1.add(opcio_no_titular);
        opcio_no_titular.setText("No titular");

        boto_inserir.setText("Inserir");
        boto_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_inserirActionPerformed(evt);
            }
        });

        boto_borrar.setText("Borrar");
        boto_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_borrarActionPerformed(evt);
            }
        });

        boto_modificar.setText("Modificar");
        boto_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boto_modificarActionPerformed(evt);
            }
        });

        Text.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        Text.setText("JUGADORS DE FÚTB");
        Text.setMaximumSize(new java.awt.Dimension(200, 17));

        Text1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        Text1.setText("L");
        Text1.setMaximumSize(new java.awt.Dimension(200, 17));

        imatge1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imatge/lliga.png"))); // NOI18N

        imatge2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imatge/pilota.png"))); // NOI18N

        Boto_sortir.setText("Sortir");
        Boto_sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boto_sortirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(boto_inserir)
                        .addGap(57, 57, 57)
                        .addComponent(boto_modificar)
                        .addGap(62, 62, 62)
                        .addComponent(boto_borrar)
                        .addGap(71, 71, 71)
                        .addComponent(Boto_sortir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Equip)
                                .addComponent(Nacionalitat, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(opcio_titular, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(Nom))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcio_no_titular)
                            .addComponent(casellaNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casellaNacionalitat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casellaEquip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salari)
                            .addComponent(Alçada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(casellaSalari, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(casellaMida)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Pes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(casellaPes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imatge2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(imatge1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Text, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(Text1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imatge2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imatge1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(casellaNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nom))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(casellaNacionalitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nacionalitat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(casellaEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Equip))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(casellaPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Salari)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(casellaMida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Alçada))
                                .addGap(18, 18, 18)
                                .addComponent(casellaSalari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcio_titular)
                    .addComponent(opcio_no_titular)
                    .addComponent(boto_borrar)
                    .addComponent(boto_modificar)
                    .addComponent(boto_inserir)
                    .addComponent(Boto_sortir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casellaNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casellaNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casellaNomActionPerformed

    private void casellaSalariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casellaSalariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casellaSalariActionPerformed

    private void borrarcaselles() {
        casellaNom.setText("");
        casellaNacionalitat.setText("");
        casellaEquip.setText("");
        casellaPes.setText("");
        casellaMida.setText("");
        casellaSalari.setText("");
        opcio_titular.setSelected(true);
    }

    private void TaulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaulaMouseClicked
        //Actualitzo la fila seleccionada.
        filaSel = Taula.getSelectedRow();

        if (filaSel == -1) {
            //Si no han selecionat cap fila desactivo els botons de borrar i modificar.
            boto_borrar.setEnabled(false);
            boto_modificar.setEnabled(false);

            //Poso les caselles en blanc.
            borrarcaselles();
        } else {
            //Si no han selecionat cap fila desactivo els botons de borrar i modificar.
            boto_borrar.setEnabled(true);
            boto_modificar.setEnabled(true);

            //Actualitzo les caselles en la informacio de la fila selecionada
            casellaNom.setText((String) Taula.getValueAt(filaSel, 1));
            casellaNacionalitat.setText((String) Taula.getValueAt(filaSel, 2));
            casellaEquip.setText((String) Taula.getValueAt(filaSel, 3));
            casellaPes.setText(String.valueOf(Taula.getValueAt(filaSel, 4)));
            casellaMida.setText(String.valueOf(Taula.getValueAt(filaSel, 5)));
            casellaSalari.setText(String.valueOf(Taula.getValueAt(filaSel, 6)));
            if ((boolean) Taula.getValueAt(filaSel, 7)) {
                opcio_titular.setSelected(true);
            } else {
                opcio_no_titular.setSelected(true);
            }
        }
    }//GEN-LAST:event_TaulaMouseClicked

    private boolean dadesCorrectes() {

        try {
            if (casellaNom.getText().trim().equals("")) {
                throw new StringIndexOutOfBoundsException();
            }
            if (casellaNacionalitat.getText().trim().equals("")) {
                throw new StringIndexOutOfBoundsException();
            }

            Integer.valueOf(casellaPes.getText().trim());
            Double.valueOf(casellaMida.getText());
            Double.valueOf(casellaSalari.getText());

        } catch (StringIndexOutOfBoundsException | NumberFormatException e) {
            return false;
        }

        return true;
    }

    private void boto_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_modificarActionPerformed

        boto_modificar.setEnabled(false);
        boto_borrar.setEnabled(false);
        //Primer miro si les dades de les caselles són correctes
        if (!dadesCorrectes()) {
            JOptionPane.showMessageDialog(this, "Dades de les caselles incorrectes!!");
            return;
        }
        //Obtenim l'índex de l'array apartir del valor de la columna 0 de la taula.
        int iArray = (int) Taula.getValueAt(filaSel, 0);
        Jugador[] array = Projecte.getArray();

        array[iArray].setNom(casellaNom.getText().trim());
        array[iArray].setNacionalitat(casellaNacionalitat.getText().trim());
        array[iArray].setEquip(casellaEquip.getText().trim());
        array[iArray].setPes(Integer.valueOf(casellaPes.getText()));
        array[iArray].setMida(Double.valueOf(casellaMida.getText()));
        array[iArray].setSalari(Double.valueOf(casellaSalari.getText()));
        array[iArray].setTitular(opcio_titular.isSelected());

        GUI_UF3.carregaTaula(new String[]{"Fila", "Nom", "Nacionalitat", "Equip", "Pes", "Alçada", "Salari", "Titular"},
                transformaDades(Projecte.getArray()), Taula);
        JOptionPane.showMessageDialog(this, "Dades modificades");

        //Poso les caselles en blanc.
        borrarcaselles();
    }//GEN-LAST:event_boto_modificarActionPerformed

    private void Boto_sortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boto_sortirActionPerformed

        Projecte.finalitzar();
        System.exit(0);
    }//GEN-LAST:event_Boto_sortirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Projecte.finalitzar();
    }//GEN-LAST:event_formWindowClosing

    private void boto_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_inserirActionPerformed
        // TODO add your handling code here:
        if (!dadesCorrectes()) {
            JOptionPane.showMessageDialog(this, "Dades de les caselles incorrectes!!");
            return;
        }
        if (casellabuida == MAX_JUGADORS) {
            JOptionPane.showMessageDialog(this, "Has introduït el màxim de jugadors");
        } else {

            Jugador[] array = Projecte.getArray();

            array[casellabuida].setNom(casellaNom.getText().trim());
            array[casellabuida].setNacionalitat(casellaNacionalitat.getText().trim());
            array[casellabuida].setEquip(casellaEquip.getText().trim());
            array[casellabuida].setPes(Integer.valueOf(casellaPes.getText()));
            array[casellabuida].setMida(Double.valueOf(casellaMida.getText()));
            array[casellabuida].setSalari(Double.valueOf(casellaSalari.getText()));
            array[casellabuida].setTitular(opcio_titular.isSelected());
            array[casellabuida].setOmplert(true);
            casellabuida++;

            GUI_UF3.carregaTaula(new String[]{"Fila", "Nom", "Nacionalitat", "Equip", "Pes", "Alçada", "Salari", "Titular"},
                    transformaDades(Projecte.getArray()), Taula);
            JOptionPane.showMessageDialog(this, "Dades introduides");
        }
        //Poso les caselles en blanc.
        borrarcaselles();
    }//GEN-LAST:event_boto_inserirActionPerformed

    private void boto_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boto_borrarActionPerformed
        //TODO add your handling code here:

        boto_borrar.setEnabled(false);
        boto_modificar.setEnabled(false);

        int iArray = (int) Taula.getValueAt(filaSel, 0);
        Jugador[] array = Projecte.getArray();
        casellabuida--;
        if (filaSel + 1 == MAX_JUGADORS) {
            array[iArray].setOmplert(false);

        } else {
            for (int i = filaSel; i < casellabuida; i++) {
                array[i] = array[i + 1];
            }
            array[casellabuida] = new Jugador();
            array[casellabuida].setOmplert(false);
        }
        GUI_UF3.carregaTaula(new String[]{"Fila", "Nom", "Nacionalitat", "Equip", "Pes", "Alçada", "Salari", "Titular"},
                transformaDades(Projecte.getArray()), Taula);
        JOptionPane.showMessageDialog(this, "Dades borrades");

        //Poso les caselles en blanc.
        borrarcaselles();
    }//GEN-LAST:event_boto_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_exemple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_exemple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_exemple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_exemple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_exemple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alçada;
    private javax.swing.JButton Boto_sortir;
    private javax.swing.JLabel Equip;
    private javax.swing.JLabel Nacionalitat;
    private javax.swing.JLabel Nom;
    private javax.swing.JLabel Pes;
    private javax.swing.JLabel Salari;
    private javax.swing.JTable Taula;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Text1;
    private javax.swing.JButton boto_borrar;
    private javax.swing.JButton boto_inserir;
    private javax.swing.JButton boto_modificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField casellaEquip;
    private javax.swing.JTextField casellaMida;
    private javax.swing.JTextField casellaNacionalitat;
    private javax.swing.JTextField casellaNom;
    private javax.swing.JTextField casellaPes;
    private javax.swing.JTextField casellaSalari;
    private javax.swing.JLabel imatge1;
    private javax.swing.JLabel imatge2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opcio_no_titular;
    private javax.swing.JRadioButton opcio_titular;
    // End of variables declaration//GEN-END:variables
}
